[package]
name = "auto4-rs"
version = "0.1.0"
authors = ["Yesterday17 <mmf@mmf.moe>"]
edition = "2018"

[dependencies]
log = "0.4"
regex = "1.5.5"
once_cell = "1.10.0"

[dependencies.mlua]
version = "0.7.4"
features = ["lua52", "vendored"]
